language: java
jdk:
  - openjdk7
before_install:
  - git submodule update --init --recursive
  - git submodule foreach "git pull origin master && git checkout master"
install: true
script:
  - mvn test
