language: java
before_script:
  - mysql -e "create database IF NOT EXISTS unifiedpush;" -uroot
  - mysql -e "create user 'unifiedpush' identified by 'unifiedpush'" -uroot
  - mysql -e "GRANT ALL ON unifiedpush.* TO 'unifiedpush';" -uroot
jdk:
    - oraclejdk7
script:
    - ./gradlew --stacktrace test -Pprofile=wildfly8mysql -PupsDatasource=mysql -PmysqlUsername=unifiedpush -PmysqlPassword=unifiedpush test
